### ISSUE TITLE
STM32G0 Programming Failed

### ISSUE THREAD

**Issue by AlexKlimaj** [florisla/stm32loader#31]
Hello, I am trying to program an STM32G0 from a Raspberry Pi using the stm32loader. I am on the latest version of master. Everything is works until it hits address 0x31 and NACK fails.

I've run it multiple times and at multiple baud rates. Always fails after 0x8020000.

Here is the error.

```
Writing ███████████████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙ 511/1087Write 256 bytes at 0x801FF00
*** Command: Write memory
    [256] bytes to write
    Write memory done
Writing ███████████████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙ 512/1087Write 256 bytes at 0x8020000
*** Command: Write memory

Traceback (most recent call last):
  File "/usr/local/bin/stm32loader", line 11, in <module>
    load_entry_point('stm32loader==0.5.0', 'console_scripts', 'stm32loader')()
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/__main__.py", line 37, in main
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/main.py", line 331, in main
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/main.py", line 184, in perform_commands
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/bootloader.py", line 588, in write_memory_data
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/bootloader.py", line 423, in write_memory
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/bootloader.py", line 263, in write_and_ack
  File "/usr/local/lib/python3.5/dist-packages/stm32loader-0.5.0-py3.5.egg/stm32loader/bootloader.py", line 647, in _wait_for_ack
stm32loader.bootloader.CommandError: NACK 0x31 address failed
```

**Comment by AlexKlimaj** [comment]
I see whats going on. The STM32G0 has a Page size of 2 Kbytes, not 1 Kbyte.

**Comment by AlexKlimaj** [comment]
Duh. I was trying to load a hex file instead of a binary... I have added the G0 to the identification list and will open a PR.
